config/routes.rb
RustCache::Application.routes.draw do
  resources :bounties

  resources :caches
  get '/caches/:id/share', to: 'caches#share', as: 'cach_share'
  post '/caches/:id/share', to: 'caches#share_create', as: 'user_caches'

  resources :locations

  resources :servers

  root :to => "home#index"

  unless ARGV.join.include?('assets:precompile')
    devise_for :users
  end
end

app/models/server.rb
class Server < ActiveRecord::Base
    def to_s
        self.name
    end
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  before_action :set_server, only: [:show, :edit, :update, :destroy]

  # GET /servers
  # GET /servers.json
  def index
    @servers = Server.all
  end

  # GET /servers/1
  # GET /servers/1.json
  def show
  end

  # GET /servers/new
  def new
    @server = Server.new
  end

  # GET /servers/1/edit
  def edit
  end

  # POST /servers
  # POST /servers.json
  def create
    @server = Server.new(server_params)

    respond_to do |format|
      if @server.save
        format.html { redirect_to @server, notice: 'Server was successfully created.' }
        format.json { render action: 'show', status: :created, location: @server }
      else
        format.html { render action: 'new' }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servers/1
  # PATCH/PUT /servers/1.json
  def update
    respond_to do |format|
      if @server.update(server_params)
        format.html { redirect_to @server, notice: 'Server was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servers/1
  # DELETE /servers/1.json
  def destroy
    @server.destroy
    respond_to do |format|
      format.html { redirect_to servers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_server
      @server = Server.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def server_params
      params.require(:server).permit(:name)
    end
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/servers/_form.html.erb
<%= simple_form_for(@server) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/servers/edit.html.erb
<h1>Editing server</h1>

<%= render 'form' %>

<%= link_to 'Show', @server %> |
<%= link_to 'Back', servers_path %>

app/views/servers/index.html.erb
<h1>Listing servers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @servers.each do |server| %>
      <tr>
        <td><%= server.name %></td>
        <td><%= link_to 'Show', server %></td>
        <td><%= link_to 'Edit', edit_server_path(server) %></td>
        <td><%= link_to 'Destroy', server, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Server', new_server_path %>

app/views/servers/new.html.erb
<h1>New server</h1>

<%= render 'form' %>

<%= link_to 'Back', servers_path %>

app/views/servers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @server.name %>
</p>

<%= link_to 'Edit', edit_server_path(@server) %> |
<%= link_to 'Back', servers_path %>