config/routes.rb
RustCache::Application.routes.draw do
  resources :bounties

  resources :caches
  get '/caches/:id/share', to: 'caches#share', as: 'cach_share'
  post '/caches/:id/share', to: 'caches#share_create', as: 'user_caches'

  resources :locations

  resources :servers

  root :to => "home#index"

  unless ARGV.join.include?('assets:precompile')
    devise_for :users
  end
end

app/models/bounty.rb
class Bounty < ActiveRecord::Base
  belongs_to :server
end

app/controllers/bounties_controller.rb
class BountiesController < ApplicationController
  before_action :set_bounty, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /bounties
  # GET /bounties.json
  def index
    @bounties = Bounty.all
  end

  # GET /bounties/1
  # GET /bounties/1.json
  def show
  end

  # GET /bounties/new
  def new
    @bounty = Bounty.new
  end

  # GET /bounties/1/edit
  def edit
  end

  # POST /bounties
  # POST /bounties.json
  def create
    @bounty = Bounty.new(bounty_params)

    respond_to do |format|
      if @bounty.save
        format.html { redirect_to @bounty, notice: 'Bounty was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bounty }
      else
        format.html { render action: 'new' }
        format.json { render json: @bounty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bounties/1
  # PATCH/PUT /bounties/1.json
  def update
    respond_to do |format|
      if @bounty.update(bounty_params)
        format.html { redirect_to @bounty, notice: 'Bounty was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bounty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bounties/1
  # DELETE /bounties/1.json
  def destroy
    @bounty.destroy
    respond_to do |format|
      format.html { redirect_to bounties_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bounty
      @bounty = Bounty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bounty_params
      params.require(:bounty).permit(:server_id, :who, :why)
    end
end

app/helpers/bounties_helper.rb
module BountiesHelper
end

app/views/bounties/_form.html.erb
<%= simple_form_for(@bounty) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :server %>
    <%= f.input :who %>
    <%= f.input :why %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bounties/edit.html.erb
<h1>Editing bounty</h1>

<%= render 'form' %>

<%= link_to 'Show', @bounty %> |
<%= link_to 'Back', bounties_path %>

app/views/bounties/index.html.erb
<h1>Listing bounties</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Server</th>
      <th>Who</th>
      <th>Why</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bounties.each do |bounty| %>
      <tr>
        <td><%= bounty.server %></td>
        <td><%= bounty.who %></td>
        <td><%= bounty.why %></td>
        <td><%= link_to 'Show', bounty %></td>
        <td><%= link_to 'Edit', edit_bounty_path(bounty) %></td>
        <td><%= link_to 'Destroy', bounty, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bounty', new_bounty_path %>

app/views/bounties/new.html.erb
<h1>New bounty</h1>

<%= render 'form' %>

<%= link_to 'Back', bounties_path %>

app/views/bounties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Server:</strong>
  <%= @bounty.server %>
</p>

<p>
  <strong>Who:</strong>
  <%= @bounty.who %>
</p>

<p>
  <strong>Why:</strong>
  <%= @bounty.why %>
</p>

<%= link_to 'Edit', edit_bounty_path(@bounty) %> |
<%= link_to 'Back', bounties_path %>