config/routes.rb
RustCache::Application.routes.draw do
  resources :bounties

  resources :caches
  get '/caches/:id/share', to: 'caches#share', as: 'cach_share'
  post '/caches/:id/share', to: 'caches#share_create', as: 'user_caches'

  resources :locations

  resources :servers

  root :to => "home#index"

  unless ARGV.join.include?('assets:precompile')
    devise_for :users
  end
end

app/models/cach.rb
class Cach < ActiveRecord::Base
  belongs_to :server

  has_many :user_cach
end

app/controllers/caches_controller.rb
class CachesController < ApplicationController
  #load_and_authorize_resource
  #skip_authorize_resource :only => [:new, :create, :index]
  before_action :set_cach, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /caches
  # GET /caches.json
  def index
    #@caches = Cach.all
    @caches = Cach.joins(:user_cach).where('user_caches.user_id'=>current_user)
  end

  # GET /caches/1
  # GET /caches/1.json
  def show
    @cache = Cach.find(params[:id])
    if !UserCach.find_by(user:current_user,cach:@cache)
      render :file => "public/401.html", :status => :unauthorized
    end
  end

  # GET /caches/new
  def new
    @cach = Cach.new
  end

  # GET /caches/1/edit
  def edit
  end

  # POST /caches
  # POST /caches.json
  def create
    @cach = Cach.new(cach_params)

    respond_to do |format|
      if @cach.save
        u_c = UserCach.new(user:current_user,cach:@cach)
        u_c.save
        format.html { redirect_to @cach, notice: 'Cach was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cach }
      else
        format.html { render action: 'new' }
        format.json { render json: @cach.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /caches/1
  # PATCH/PUT /caches/1.json
  def update
    respond_to do |format|
      if @cach.update(cach_params)
        format.html { redirect_to @cach, notice: 'Cach was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cach.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /caches/1
  # DELETE /caches/1.json
  def destroy
    @cach.destroy
    respond_to do |format|
      format.html { redirect_to caches_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cach
      @cach = Cach.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cach_params
      params.require(:cach).permit(:server_id, :location_id, :secured, :notes)
    end 

    def has_permission
        
    end
end

app/helpers/caches_helper.rb
module CachesHelper
end

app/views/caches/_form.html.erb
<%= simple_form_for(@cach) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :server %>
    <%= f.input :name %>
    <%= f.input :x %>
    <%= f.input :y %>
    <%= f.input :z %>
    <%= f.input :secured %>
    <%= f.input :notes %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/caches/_share_form.html.erb
<%= simple_form_for(@user_cach) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user %>
    <%= f.hidden_field :cach %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/caches/edit.html.erb
<h1>Editing cach</h1>

<%= render 'form' %>

<%= link_to 'Show', @cach %> |
<%= link_to 'Back', caches_path %>

app/views/caches/index.html.erb
<h1>Listing caches</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Server</th>
      <th>Name</th>
      <th>X</th>
      <th>Y</th>
      <th>Z</th>
      <th>Secured</th>
      <th>Notes</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @caches.each do |cach| %>
      <tr>
        <td><%= cach.server %></td>
        <td><%= cach.name %></td>
        <td><%= cach.x %></td>
        <td><%= cach.y %></td>
        <td><%= cach.z %></td>
        <td><%= cach.secured %></td>
        <td><%= cach.notes %></td>
        <td><%= link_to 'Show', cach %></td>
        <td><%= link_to 'Share', cach_share_path(cach) %></td>
        <td><%= link_to 'Edit', edit_cach_path(cach) %></td>
        <td><%= link_to 'Destroy', cach, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cache', new_cach_path %>

app/views/caches/new.html.erb
<h1>New cache</h1>

<%= render 'form' %>

<%= link_to 'Back', caches_path %>

app/views/caches/share.html.erb
<h1>Editing cache</h1>

<%= render 'share_form' %>

<%= link_to 'Share', cach_share_path(@cach) %>

<%= link_to 'Show', @cach %> |
<%= link_to 'Back', caches_path %>

app/views/caches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Server:</strong>
  <%= @cach.server %>
</p>

<p>
  <strong>Name:</strong>
  <%= @cach.name %>
</p>

<p>
  <strong>X:</strong>
  <%= @cach.x %>
</p>

<p>
  <strong>Y:</strong>
  <%= @cach.y %>
</p>

<p>
  <strong>Z:</strong>
  <%= @cach.z %>
</p>

<p>
  <strong>Secured:</strong>
  <%= @cach.secured %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @cach.notes %>
</p>

<h3>Shared with</h3>
<ul>
  <% @cach.user_cach.each do |uc| %>
    <li><%= uc.user.email %></li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_cach_path(@cach) %> |
<%= link_to 'Back', caches_path %>